### ISSUE TITLE
 error in logs

### ISSUE THREAD

**Issue by garywilson4** [bertbert72/HomeAssistant_VirginTivo#56] opened 2020-05-30 13:12 UTC
getting this error in the logs
 
`Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:938
Integration: Media Player (documentation, issues)
First occurred: 10:41:47 (1 occurrences)
Last logged: 10:41:47

MediaPlayerDevice is deprecated, modify VirginTivo to extend MediaPlayerEntity`

**Comment by ColinRobbins** [comment] 2020-06-07 14:59
Duplicate of [issue 55](https://github.com/bertbert72/HomeAssistant_VirginTivo/issues/57) - sorry didn’t see this before I opened a new one.
There is a pull request that should fix it.

**Closed** 2020-06-08 17:42 UTC
